steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'entrypoint', '.']
  env:
  - 'PROJECT_ROOT=github.com/WasinWatt/go-rest-api
  - 'GOOS=linux'
  - 'GOARCH=amd64'
  - 'CGO_ENABLED=0'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-rest-api:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/go-rest-api:$COMMIT_SHA']
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['set', 'image', '$_RESOURCE', '$_CONTAINER=gcr.io/$PROJECT_ID/go-rest-api:$COMMIT_SHA']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
